/* build-Linux-amigaos3/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 NetSurf Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "df0f5bcfb5ef3c8ad6cbe697e7b7465e"

/* Revision testament checksum:
 * MD5:df0f5bcfb5ef3c8ad6cbe697e7b7465e
 */

/* Revision testament: */
#define USERNAME "root"
#define GECOS "root"
#define WT_ROOT "/usr/local/netsurf/"
#define WT_HOSTNAME "ubuntu"
#define WT_COMPILEDATE "14.03.2016"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "6991a42cdd00efa5d5981a3780c2bd3521e4627e"
#define WT_MODIFIED 0
#define WT_MODIFICATIONS {\
 \
}

#endif
