/* build-AmigaOS-amigaos3/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 NetSurf Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "6e3d46bb59a7a4ae171880eb0c7b16cd"

/* Revision testament checksum:
 * MD5:6e3d46bb59a7a4ae171880eb0c7b16cd
 */

/* Revision testament: */
#define USERNAME "root"
#define GECOS "root"
#define WT_ROOT "/usr/local/netsurf/"
#define WT_HOSTNAME "ubuntu"
#define WT_COMPILEDATE "08.03.2016"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "6991a42cdd00efa5d5981a3780c2bd3521e4627e"
#define WT_MODIFIED 0
#define WT_MODIFICATIONS {\
 \
}

#endif
